### ISSUE TITLE
Image构建容器后出现问题

### ISSUE THREAD

**Issue by wangyiyang** [hangxin1940/docker-elasticsearch-cn#1]
```
Starting Elasticsearch with the options -Des.path.data=/data   -Des.path.logs=/logs   -Des.transport.tcp.port=9300   -Des.http.port=9200
Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root.
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:93)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:144)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

使用命令：
docker run -d -p 9200:9200 -p 9300:9300 hangxin1940/docker-elasticsearch-cn:v2.1.1

**Comment by hangxin1940** [comment]
ES不允许使用root直接运行了。

我是这样运行的
```
RUN useradd elsusr && adduser elsusr sudo && \
    echo "elsusr:elsusr" | chpasswd && \
    chown -R elsusr /elasticsearch && chown -R elsusr /data && chown -R elsusr /logs
USER elsusr
CMD ["/elasticsearch/bin/docker-start"]
```
